// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// tree-parser.cpp
SEXP cpp_parse_one_file();
extern "C" SEXP _pkgsimil_cpp_parse_one_file() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_parse_one_file());
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_pkgsimil_cpp_parse_one_file", (DL_FUNC) &_pkgsimil_cpp_parse_one_file, 0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pkgsimil(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
