// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// testcpp.cpp
cpp11::doubles cpp_test_fn(doubles x);
extern "C" SEXP _pkgsimil_cpp_test_fn(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_test_fn(cpp11::as_cpp<cpp11::decay_t<doubles>>(x)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP c_parse_one_file(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_pkgsimil_cpp_test_fn", (DL_FUNC) &_pkgsimil_cpp_test_fn, 1},
    {"c_parse_one_file",      (DL_FUNC) &c_parse_one_file,      2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pkgsimil(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
