// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// tree-similarity.cpp
writable::doubles cpp_tree_similarity(strings x, const bool verbose);
extern "C" SEXP _pkgsimil_cpp_tree_similarity(SEXP x, SEXP verbose) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_tree_similarity(cpp11::as_cpp<cpp11::decay_t<strings>>(x), cpp11::as_cpp<cpp11::decay_t<const bool>>(verbose)));
  END_CPP11
}

extern "C" {
/* .Call calls */
extern SEXP c_parse_one_file(SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_pkgsimil_cpp_tree_similarity", (DL_FUNC) &_pkgsimil_cpp_tree_similarity, 2},
    {"c_parse_one_file",              (DL_FUNC) &c_parse_one_file,              2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_pkgsimil(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
