#' Load embeddings generated by the \link{pkgsimil_embeddings_raw} function,
#' either for all rOpenSci packages or, if `fns = TRUE`,  all individual
#' functions within those packages.
#'
#' @param fns If `FALSE` (default), load embeddings for all rOpenSci packages;
#' otherwise load (considerably larger dataset of) embeddings for all
#' individual functions.
#' @export
pkgsimil_load_embeddings <- function (fns = FALSE) {
    fname <- ifelse (fns, "embeddings-fns.Rds", "embeddings.Rds")
    fname <- fs::path (pkgsimil_cache_path (), fname)
    if (!fs::file_exists (fname)) {
        fname <- pkgsimil_dl_embeddings (fns = fns)
    }
    readRDS (fname)
}

pkgsimil_dl_embeddings <- function (fns = FALSE) {

    url_base <- "https://github.com/ropensci-review-tools/pkgsimil/releases/download/"
    version <- "v0.1.2"
    file <- ifelse (fns, "embeddings-fns.Rds", "embeddings.Rds")
    url <- paste0 (url_base, version, "/", file)

    destfile <- fs::path (pkgsimil_cache_path (), file)
    utils::download.file (url, destfile = destfile)
    return (destfile)
}
