#' Load embeddings generated by the \link{pkgsimil_embeddings_from_pkgs}
#' function, either for all rOpenSci packages or, if `fns = TRUE`,  all
#' individual functions within those packages.
#'
#' @inheritParams pkgsimil_similar_pkgs
#' @param what Either "embeddings" to load pre-generated embeddings, "idfs" to
#' load pre-generated Inverse Document Frequency weightings, or "functions" to
#' load pre-generated frequency tables for function calls.
#' @param fns If `FALSE` (default), load embeddings for all rOpenSci packages;
#' otherwise load (considerably larger dataset of) embeddings for all
#' individual functions.
#' @return The loaded `data.frame`.
#' @export
#'
#' @examples
#' \dontrun{
#' embeddings <- pkgsimil_load_data ("embeddings")
#' embeddings_fns <- pkgsimil_load_data ("embeddings", fns = TRUE)
#' idfs <- pkgsimil_load_data ("idfs")
#' idfs_fns <- pkgsimil_load_data ("idfs", fns = TRUE)
#' }
pkgsimil_load_data <- function (what = "embeddings", corpus = "ropensci", fns = FALSE) {

    fname <- get_cache_file_name (what, corpus, fns)

    fname <- fs::path (pkgsimil_cache_path (), fname)
    if (!fs::file_exists (fname)) {
        fname <- pkgsimil_dl_data (what = what, corpus = corpus, fns = fns)
    }
    readRDS (fname)
}

get_cache_file_name <- function (what, corpus, fns) {

    corpus <- match.arg (corpus, c ("ropensci", "cran"))
    what <- match.arg (what, c ("embeddings", "idfs", "functions"))

    if (corpus == "ropensci") {

        fname <- switch (what,
            "embeddings" = ifelse (fns, "embeddings-fns.Rds", "embeddings.Rds"),
            "idfs" = ifelse (fns, "bm25-ropensci-fns.Rds", "bm25-ropensci.Rds"),
            "functions" = "fn-calls-ropensci.Rds"
        )

    } else if (corpus == "cran") {

        fname <- switch (what,
            "embeddings" = "embeddings-cran.Rds",
            "idfs" = "bm25-cran.Rds",
            "functions" = "fn-calls-cran.Rds"
        )
    }

    return (fname)
}

# nocov start
pkgsimil_dl_data <- function (what = "embeddings", corpus = "ropensci", fns = FALSE) {

    fname <- get_cache_file_name (what, corpus, fns)

    url_base <-
        "https://github.com/ropensci-review-tools/pkgsimil/releases/download/"
    version <- "v0.1.2"

    dl_url <- paste0 (url_base, version, "/", fname)

    destfile <- fs::path (pkgsimil_cache_path (), fname)
    curl::curl_download (url = dl_url, destfile = destfile, quiet = opt_is_quiet ())
    return (destfile)
}
# nocov end

pkgsimil_cache_path <- function () {

    cache_dir <- Sys.getenv ("PKGSIMIL_CACHE_DIR")

    if (cache_dir == "") { # nocov start
        cache_dir <- fs::path_expand (fs::path (
            rappdirs::user_cache_dir (),
            "R",
            "pkgsimil"
        ))
        if (!fs::dir_exists (cache_dir)) {
            fs::dir_create (cache_dir, recurse = TRUE)
        }
    } # nocov end

    return (cache_dir)
}
