# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_bm25 <- function (idfs, tokens, tokens_i) {
    .Call (`_pkgsimil_rcpp_bm25`, idfs, tokens, tokens_i)
}
