#' Find R packages matching an input of either text or another package
#'
#' @description This function accepts as `input` either a text description, or
#' a path to a local R package, and returns information on R packages which
#' best match that input. Matches are found from within a specified "corpus",
#' currently all packages from either [rOpenSci's package
#' suite](https://ropensci.org/packages), or from
#' [CRAN](https://cran.r-project.org).
#'
#' The returned object has a default `print` method which prints the best 5
#' matches directly to the screen, yet returns information on all packages
#' within the specified corpus. This information is in the form of a
#' `data.frame`, with one column for the package name, and one or more
#' additional columns of integer ranks for each package. There is also a `head`
#' method to print the first few entries of these full data (default `n = 5`).
#' To see all data, use `as.data.frame()`.
#'
#' Ranks are obtained from scores derived from:
#' \itemize{
#' \item Cosine similarities between Large Language Model (LLM) embeddings for
#' the `input`, and corresponding embeddings for the specified corpus.
#' \item ["Best Match 25" (BM25)](https://en.wikipedia.org/wiki/Okapi_BM25)
#' scores based on document token frequencies.
#' }
#'
#' Ranks for text matches are generally obtained from packages both including
#' and excluding function descriptions as part of the package text. This
#' results in up to four scores for each input. These scores are then combined
#' to a final ranking using the [Reciprocal Rank Fusion (RRF)
#' algorithm](https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf). The
#' additional parameter of `llm_proportion` determines the extent to which the
#' final ranking weights the LLM versus BM25 components.
#'
#' Finally, all components of this function are locally cached for each call
#' (by the \pkg{memoise} package), so additional calls to this function with
#' the same `input` and `corpus` should be much faster than initial calls. This
#' means the effect of changing `llm_proportion` can easily be examined by
#' simply repeating calls to this function.
#'
#' @param input Either a path to local source code of an R package, or a text
#' string.
#' @param corpus If `embeddings` or `idfs` parameters are not specified, they
#' are automatically downloaded for the corpus specified by this parameter.
#' Must be one of "ropensci" or "cran". The function will then return the most
#' similar package from the specified corpus.
#' @param embeddings Large Language Model embeddings for all rOpenSci packages,
#' generated from \link{pkgmatch_embeddings_from_pkgs}. If not provided,
#' pre-generated embeddings will be downloaded and stored in a local cache
#' directory.
#' @param idfs Inverse Document Frequency tables for all rOpenSci packages,
#' generated from \link{pkgmatch_bm25}. If not provided, pre-generated IDF
#' tables will be downloaded and stored in a local cache directory.
#' @param input_is_code A binary flag indicating whether `input` is code or
#' plain text. Ignored if `input` is path to a local package; otherwise can be
#' used to force appropriate interpretation if input type.
#' @param llm_proportion A value between 0 and 1 to control the relative
#' contributions of results from Large Language Models ("LLMs") versus results
#' from traditional token-frequency models. Final rankings are generated by
#' combining these two kinds of results, so that `llm_proportion = 0` will
#' return results from token frequency analyses only, while
#' `llm_proportion = 1` will return results from LLMs only.
#' @param n When the result of this function is printed to screen, the top `n`
#' packages will be displayed.
#'
#' @return A `data.frame` with a "package" column naming packages, and one or
#' more columns of package ranks in terms of text similarity and, if `input` is
#' a local path to an entire R package, of similarity in code structure. As
#' described above, the default `print` method prints package names only. To
#' see full result, use `as.data.frame()`.
#'
#' @note The first time this function is run without passing either
#' `embeddings` or `idfs`, required values will be automatically downloaded and
#' stored in a locally persistent cache directory. Especially for the "cran"
#' corpus, this downloading may take quite some time.
#'
#' @seealso input_is_code
#'
#' @family main
#' @export
#'
#' @examples
#' \dontrun{
#' input <- "Download open spatial data from NASA"
#' p <- pkgmatch_similar_pkgs (input)
#' p # Default print method, lists 5 best matching packages
#' head (p) # Shows first 5 rows of full `data.frame` object
#' # This second call will be much faster than first call:
#' p2 <- pkgmatch_similar_pkgs (input, llm_proportion = 0.25)
#' }
pkgmatch_similar_pkgs <- function (input,
                                   corpus = "ropensci",
                                   embeddings = NULL,
                                   idfs = NULL,
                                   input_is_code = text_is_code (input),
                                   llm_proportion = 0.5,
                                   n = 5L) {

    code <- NULL # Supress no visible binding note

    corpus <- match.arg (corpus, c ("ropensci", "cran"))

    if (is.null (embeddings)) {
        embeddings <- pkgmatch_load_data (what = "embeddings", corpus = corpus)
    }
    nms_expected <- c ("text_with_fns", "text_wo_fns", "code")
    stopifnot (is.list (embeddings))
    stopifnot (identical (names (embeddings), nms_expected))

    if (is.null (idfs)) {
        idfs <- pkgmatch_load_data (what = "idfs", corpus = corpus)
    }
    stopifnot (is.list (idfs))
    stopifnot (identical (names (idfs), c ("idfs", "token_lists")))

    if (input_is_path (input)) {

        res <- similar_pkgs_from_pkg (input, embeddings)
        # Then add BM25 from package text:
        txt_with_fns <- get_pkg_text (input)
        txt_wo_fns <- rm_fns_from_pkg_txt (txt_with_fns) [[1]]
        bm25_with_fns <-
            pkgmatch_bm25 (txt_with_fns, idfs = idfs, corpus = corpus)
        bm25_wo_fns <- pkgmatch_bm25 (txt_wo_fns, idfs = idfs, corpus = corpus)
        # bm25 fn returns measures against idfs with and without fns:
        bm25_with_fns$bm25_wo_fns <- NULL
        bm25_wo_fns$bm25_with_fns <- NULL
        bm25_text <- dplyr::left_join (bm25_with_fns, bm25_wo_fns, by = "package")
        res <- dplyr::left_join (res, bm25_text, by = "package") |>
            dplyr::relocate (code, .after = dplyr::last_col ())

        # Then combine BM25 from function calls with "code" similarities:
        bm25_code <- pkgmatch_bm25_fn_calls (input, corpus = corpus) |>
            dplyr::rename (bm25_code = "bm25")

        res <- dplyr::left_join (res, bm25_code, by = "package")

        rm_fn_data <- TRUE # TODO: Expose that parameter

    } else {

        res <- similar_pkgs_from_text (
            input = input,
            embeddings = embeddings,
            idfs = idfs,
            corpus = corpus,
            input_is_code = input_is_code
        )

        rm_fn_data <- !input_mentions_functions (input)

    }

    res <- pkgmatch_rerank (res, rm_fn_data, llm_proportion)

    class (res) <- c ("pkgmatch", class (res))
    attr (res, "n") <- as.integer (n)

    return (res)
}

similar_pkgs_from_pkg <- function (input, embeddings) {

    m_similar_pkgs_from_pkg (input, embeddings)
}

similar_pkgs_from_pkg_internal <- function (input, embeddings) {

    op <- options ()
    options (rlib_message_verbosity = "quiet")

    emb <- pkgmatch_embeddings_from_pkgs (input)

    options (op)

    d_text <- lapply (
        c ("text_with_fns", "text_wo_fns"),
        function (what) {
            npkgs <- ncol (embeddings [[what]])
            nrow <- nrow (emb [[what]])
            emb_text <- matrix (emb [[what]], nrow = nrow, ncol = npkgs)
            d_text <- colSums (sqrt ((emb_text - embeddings [[what]])^2))
            d_text <- data.frame (package = names (d_text), text = unname (d_text))
            names (d_text) [2] <- what
            return (d_text)
        }
    )
    d_text <- dplyr::left_join (d_text [[1]], d_text [[2]], by = "package")

    nrow <- nrow (embeddings$code)
    npkgs <- ncol (embeddings$code)
    emb_code <- matrix (emb$code, nrow = nrow, ncol = npkgs)
    d_code <- colSums (sqrt ((emb_code - embeddings$code)^2))
    d_code <- data.frame (package = names (d_code), code = unname (d_code))

    out <- dplyr::left_join (d_text, d_code, by = "package")
    out$code <- out$code / max (out$code, na.rm = TRUE)
    out$text_with_fns <- out$text_with_fns / max (out$text_with_fns, na.rm = TRUE)
    out$text_wo_fns <- out$text_wo_fns / max (out$text_wo_fns, na.rm = TRUE)

    return (out)
}
m_similar_pkgs_from_pkg <- memoise::memoise (similar_pkgs_from_pkg_internal)

order_output <- function (out, what = "text") {

    index <- order (out [[what]])
    out <- out [index, c ("package", what)]
    rownames (out) <- NULL

    return (out)
}

similar_pkgs_from_text <- function (input,
                                    embeddings = NULL,
                                    idfs = NULL,
                                    corpus = "ropensci",
                                    input_is_code = text_is_code (input)) {

    stopifnot (is.character (input))
    stopifnot (length (input) == 1L)

    if (is.null (embeddings)) {
        embeddings <- pkgmatch_load_data (what = "embeddings", corpus = corpus)
    }
    if (input_is_code) {
        similarities <- similarity_embeddings (
            input,
            embeddings$code,
            input_is_code = TRUE
        )
    } else {
        similarities <- similarity_embeddings (
            input,
            embeddings,
            input_is_code = FALSE
        )
    }

    similarities_bm25 <-
        pkgmatch_bm25 (input = input, idfs = idfs, corpus = corpus)

    similarities <- dplyr::left_join (
        similarities,
        similarities_bm25,
        by = "package"
    )
    similarities [is.na (similarities)] <- 0

    return (similarities)
}

input_mentions_functions <- function (input) {

    stopifnot (length (input) == 1L)

    grepl ("\\sfunction\\s", input, ignore.case = TRUE)
}
